name: C++ CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ make
          sudo apt-get install -y lcov

      - name: Build and test
        run: |
          mkdir build
          cd build
          cmake ..
          make
          make test

  coverage:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ make
          sudo apt-get install -y lcov

      - name: Build and run coverage
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug ..
          make
          ctest
          lcov --capture --directory . --output-file coverage.info        
          lcov --list coverage.info

          - name: Upload coverage to Codecov
          uses: codecov/codecov-action@v2
          env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          with:
          file: ./build/coverage.info
          slug: jiku1797/ring_buffer
